name: ci

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
         go: [1.11]
         flag: [A]
    timeout-minutes: 360
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login
        run: |
            lscpu
